stage_read:
  raw_data_path: "data/raw/Volga-Ural Interfluve, Russia/1000 Cranes. Russia. Volga-Ural Interfluve..csv"
  irregularly_sampled_data_path: "data/interim/irregularly_sampled_data.csv"
  min_count: 1000
  max_latitude: 18.5

stage_rw:
  regularly_sampled_data_path: "data/interim/regularly_sampled_data.csv"
  time_step_hours: 6
  gap_split_days: 7
  min_points: 20

stage_stopover:
  stopover_sites_output_path: "outputs/stopover/stopover_sites.csv"
  stopover_events_output_path: "outputs/stopover/stopover_events.csv"
  site_contributors_output_path: "outputs/stopover/site_contributors.csv"
  stopover_atlas_path: "outputs/stopover/stopover_atlas.html"
  r_stop_km: 10.0
  min_stop_hours: 48.0
  site_eps_km: 20
  min_samples: 2

  show_stopover_atlas: false

stage_phenology:
  plots_out_dir: "outputs/phenology"
  migration_summary_output_path: "outputs/phenology/migration_summary.csv"
  individuals_summary_output_path: "outputs/phenology/individuals_summary.csv"
  population_summary_output_path: "outputs/phenology/population_summary.csv"

  hull_margin_km: 50.0
  winter_months: [12, 1, 2]
  breeding_months: [5, 6, 7, 8]
  min_points_winter: 10
  min_points_breeding: 10

  major_stopover_hours: 48.0
  gap_split_days: 7.0

  winter_start_month_day: [11, 1]
  winter_end_month_day: [2, 1]
  summer_start_month_day: [4, 30]
  summer_end_month_day: [7, 31]
  departure_confirm_days: 21
  link_radius_km: 500

  plots_dpi: 180
  max_points_scatter: 20000

stage_corridor:
  irregularly_sampled_migration_only_data_path: "data/interim/irregularly_sampled_migration_only_data.csv"
  spring_migration_start_month: 3
  spring_migration_end_month: 6
  fall_migration_start_month: 8
  fall_migration_end_month: 11

  proj_crs: "+proj=cea +lon_0=0 +lat_ts=0 +datum=WGS84 +units=m +no_defs"
  cellsize_m: 5000
  extent_buffer_m: 250000
  location_error_m: 30
  window_size: 31
  margin: 11
  time_step_mins: 60
  max_points_plot: 200000
  corridors_path: "outputs/corridors/corridors.html"
  corridor_95_output_path: "outputs/corridors/corridor_95.geojson"
  corridor_50_output_path: "outputs/corridors/corridor_50.geojson"
